games/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required
from app import db, requires_roles
from models import Student, School

games_blueprint = Blueprint('games', __name__, template_folder='templates')


# view turtle game
@games_blueprint.route('/turtle_game')
@login_required
@requires_roles('student')
def turtle_game():
    return render_template('turtleGame.html')


# view pollution game
@games_blueprint.route('/pollution_game')
@login_required
@requires_roles('student')
def pollution_game():
    return render_template('pollutionGame.html')


@games_blueprint.route('/submitScore', methods=['POST'])
def submit_score():
    if request.method == 'POST':
        score = 1
        game = "No Game Specified"
        success = True
        errors = []

        if "sourceGame" in request.form:
            game = request.form.get("sourceGame")

            # source game names
            # kieran's game - TurtleGame
            # charlie's game - PollutionGame
        else:
            success = False
            errors.append("noSourceGame")
        if "score" in request.form:
            score = int(round(float(request.form.get("score"))))
        else:
            success = False
            errors.append("noScore")
        if "checkSum" in request.form:

            check_sum = float(request.form.get("checkSum"))

            # key values for checksum, same values are hard coded into each game's scoring scripts.
            s1 = 541
            s2 = 225

            # checksum is calculated  as ((s1+score)*s2)*s1), so to check, do
            # ((check_sum/s1)/s2)-s1), and it should equal score.
            # this is not very secure, but for a kids website this level of security
            # for high scores is sufficient, and will make it at least tamper proof
            score2 = round(((check_sum / s1) / s2) - s1)
            if not score2 == score:
                success = False
                score = -1
                errors.append("checksumFalse")
        else:
            success = False
            errors.append("noCheckSum")

        if not current_user.is_authenticated:
            success = False
            errors.append("noUserLoggedIn")

        if success:
            print("Received score from " + game + ", of " + str(score), ", is legitimate.")

            # put code here for saving a correct score from the game
            save_score(score)

        else:
            print("Received score from " + game + ", of " + str(score),
                  "but with Errors: [" + ", ".join(errors)+"]. Score will not be saved.")

    response = {
        "errors": errors,
        "success": success,
        "score": score,
        "game": game
    }
    return response


def save_score(score):
    if current_user.is_authenticated:
        if current_user.Role == 'student':
            # update user's score
            user = Student.query.filter_by(Username=current_user.Username).first()
            previous_score = user.Points
            new_score = previous_score + score
            user.Points = new_score

            # update the schools total score
            users_school = School.query.filter_by(SIC=user.SIC).first()
            school_old_score = users_school.TotalPoints
            new_school_score = school_old_score + score
            users_school.TotalPoints = new_school_score

            db.session.commit()
        else:
            print("Score can only be saved if you are a student")
    else:
        print("No user logged in, score not saved.")

leaderboard/views.py
from flask import *
from sqlalchemy import desc
from models import Student

# config
lb_blueprint = Blueprint('leaderboard', __name__, template_folder='templates')


@lb_blueprint.route('/leaderboard')
def leaderboard():
    try:
        students = Student.query.order_by((desc(Student.Points))).all()
        return render_template('leaderboard.html', Students=students)
    except Exception as e:
        # e holds description of the error
        error_text = "<p>The error:<br>" + str(e) + "</p>"
        hed = '<h1>Something is broken.</h1>'
        return hed + error_text

parents/views.py
from app import requires_roles
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from models import Student, Parent, School, Teacher

# CONFIG
parent_blueprint = Blueprint('parents', __name__, template_folder='templates')


# VIEWS
# parentViewStudent: displays the page which tells the parent about their child
@parent_blueprint.route('/parentViewStudent')
@login_required
@requires_roles('parent')
def parent_view_student():
    parent = Parent.query.filter_by(Email=current_user.Username).first()
    student = Student.query.filter_by(StudentID=parent.StudentID).first()

    school = School.query.filter_by(SIC=student.SIC).first()
    teacher = Teacher.query.filter_by(TeacherID=student.TeacherID).first()
    return render_template('parentViewStudent.html',
                           student=student, school=school, teacher=teacher)

students/views.py
# IMPORTS
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, login_required, logout_user

from app import db
from models import Student, Teacher, School, Parent, User
from students.forms import StudentRegForm, TeacherRegForm, ParentRegForm, LoginForm
from werkzeug.security import check_password_hash, generate_password_hash

# CONFIG
users_blueprint = Blueprint('students', __name__, template_folder='templates')


# VIEWS
# view registration
@users_blueprint.route('/student_register', methods=['GET', 'POST'])
def student_register():
    # create signup form object
    form = StudentRegForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        # if username already exists redirect user back to signup page with error message so user can try again
        user = Student.query.filter_by(Username=form.username.data).first()
        if user:
            flash('Username already exists, go to the login page')
            return render_template('studentRegister.html', form=form)

        # if teacher id doesn't exist, then the user can't register
        teacher = Teacher.query.filter_by(TeacherID=form.teacher_id.data).first()
        if not teacher:
            flash('That Teacher ID does not exist')
            return render_template('studentRegister.html', form=form)

        # if sic doesn't exits, then the user can't register
        sic = School.query.filter_by(SIC=form.sic.data).first()
        if not sic:
            flash('That SIC does not exist')
            return render_template('studentRegister.html', form=form)

        hashed_password = generate_password_hash(form.password.data)

        # create a new user with the form data
        new_user = Student(FirstName=form.firstname.data,
                           LastName=form.lastname.data,
                           SIC=form.sic.data,
                           TeacherID=form.teacher_id.data,
                           Password=hashed_password,
                           Username=form.username.data)

        new_student = User(Username=form.username.data,
                           Password=hashed_password,
                           Role='student')

        # add the new user to the database
        db.session.add(new_user)
        db.session.add(new_student)
        db.session.commit()

        # sends user to login page
        return redirect(url_for('students.login'))
    # if request method is GET or form not valid re-render signup page
    return render_template('studentRegister.html', form=form)


@users_blueprint.route('/parent_register', methods=['GET', 'POST'])
def parent_register():
    form = ParentRegForm()

    if form.validate_on_submit():
        user = Parent.query.filter_by(Email=form.email.data).first()
        if user:
            flash('Email already exists, go to the login page')
            return render_template('parentRegister.html', form=form)

        # if sic doesn't exits, then the user can't register
        sic = School.query.filter_by(SIC=form.sic.data).first()
        if not sic:
            flash('That SIC does not exist')
            return render_template('parentRegister.html', form=form)

        # if student id doesn't exits, then the user can't register
        student_id = Student.query.filter_by(StudentID=form.student_id.data).first()
        if not student_id:
            flash('That Student does not exist')
            return render_template('parentRegister.html', form=form)

        hashed_password = generate_password_hash(form.password.data)

        # create a new user with the form data
        new_user = Parent(FirstName=form.firstname.data,
                          LastName=form.lastname.data,
                          SIC=form.sic.data,
                          StudentID=form.student_id.data,
                          Email=form.email.data,
                          Password=hashed_password)

        new_parent = User(Username=form.email.data,
                          Password=hashed_password,
                          Role='parent')

        # add the new user to the database
        db.session.add(new_user)
        db.session.add(new_parent)
        db.session.commit()

        return redirect(url_for('students.login'))
    return render_template('parentRegister.html', form=form)


@users_blueprint.route('/teacher_register', methods=['GET', 'POST'])
def teacher_register():
    form = TeacherRegForm()

    if form.validate_on_submit():
        user = Teacher.query.filter_by(Email=form.email.data).first()
        if user:
            flash('Email already exists, go to the login page')
            return render_template('teacherRegister.html', form=form)

        # if sic doesn't exits, then the user can't register
        sic = School.query.filter_by(SIC=form.sic.data).first()
        if not sic:
            flash('That SIC does not exist')
            return render_template('teacherRegister.html', form=form)

        hashed_password = generate_password_hash(form.password.data)

        # create a new user with the form data
        new_user = Teacher(FirstName=form.firstname.data,
                           LastName=form.lastname.data,
                           SIC=form.sic.data,
                           Password=hashed_password,
                           Email=form.email.data)

        new_teacher = User(Username=form.email.data,
                           Password=hashed_password,
                           Role='teacher')

        # add the new user to the database
        db.session.add(new_user)
        db.session.add(new_teacher)
        db.session.commit()

        return redirect(url_for('students.login'))
    return render_template('teacherRegister.html', form=form)


# Login page
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        # Redirect the user to an unauthorised notice!
        return render_template('403.html')

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(Username=form.username.data).first()

        if not user or not check_password_hash(user.Password, form.password.data):
            flash('Please check your login details and try again')
            return render_template('login.html', form=form)
        login_user(user)

        return account()
    return render_template('login.html', form=form)


# view accounts page
@users_blueprint.route('/account')
@login_required
def account():
    if current_user.Role == 'student':
        user = Student.query.filter_by(Username=current_user.Username).first()
        usertype = 'Username'
        username = user.Username
    elif current_user.Role == 'teacher':
        user = Teacher.query.filter_by(Email=current_user.Username).first()
        usertype = 'Email'
        username = user.Email
    else:
        user = Parent.query.filter_by(Email=current_user.Username).first()
        usertype = 'Email'
        username = user.Email
    name = user.FirstName + ' ' + user.LastName
    sic = user.SIC
    school = School.query.filter_by(SIC=user.SIC).first()
    school_name = school.SchoolName
    return render_template('account.html', name=name, usernameEmail=usertype,
                           user=username, SIC=sic, schoolName=school_name, role=current_user.Role.capitalize())


# about goal 14 page
@users_blueprint.route('/about')
def about():
    return render_template('about.html')


# home page when not logged in
@users_blueprint.route('/index')
def index():
    return render_template('index.html')


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

teachers/views.py
from app import requires_roles, db
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from models import Student, Teacher, User
from students.forms import ResetPasswordForm
from werkzeug.security import check_password_hash, generate_password_hash

# CONFIG
teacher_blueprint = Blueprint('teachers', __name__, template_folder='templates')


# VIEWS
# teacher_view_school: lets a teacher account view all students from that school
@teacher_blueprint.route('/teacherViewSchool')
@login_required
@requires_roles('teacher')
def teacher_view_school():
    teacher = Teacher.query.filter_by(Email=current_user.Username).first()
    students = Student.query.filter_by(SIC=teacher.SIC).all()

    return render_template('teacherViewSchool.html',
                           Students=students)


# reset_password: allows a teacher account to reset a password for a student from their school
@teacher_blueprint.route('/resetPassword', methods=['GET', 'POST'])
@login_required
@requires_roles('teacher')
def reset_password():
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # gets the student that matches the Student ID input in the form
        student_to_change = Student.query.filter_by(StudentID=form.student_id.data).first()
        if not student_to_change:  # if the student doesn't exist
            flash("This student doesn't exist, or doesn't go to your school. Please try again")
            return render_template('reset_password.html', form=form)

        # gets the current user's (must be a teacher) email address, for use in the if statement
        current_teacher = Teacher.query.filter_by(Email=current_user.Username).first()
        if student_to_change.SIC != current_teacher.SIC:  # if the student and teacher's schools don't match
            flash("This student doesn't exist, or doesn't go to your school. Please try again")
            return render_template('reset_password.html', form=form)

        # gets the record in the 'Users' table, which is the way the program manages logins
        user_to_change = User.query.filter_by(Username=student_to_change.Username).first()

        hashedPassword = generate_password_hash(form.password.data)

        # updates both records, one in either table, and commits the change to the database
        student_to_change.Password = hashedPassword
        user_to_change.Password = hashedPassword
        db.session.commit()

        return redirect(url_for('teachers.teacher_view_school'))

    return render_template('reset_password.html', form=form)

templates/405.html
{% extends "base.html" %}

{% block content %}

    <div class="errorBox">Error 405 - Method not allowed.</div>

{% endblock %}

templates/account.html
{% extends "base.html" %}

{% block content %}

    <div class="accountBox">
        <h1 class="center">
            {{ name }}'s account
        </h1>
        <div class="accountInfo">
            {{ usernameEmail }}: {{ user }} <br>
            School Individual Code: {{ SIC }} <br>
            School Name: {{ schoolName }}<br>
            Role: {{ role }}
        </div>
    </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>


<body class="backgroundImage">
<div class="computer">
    <div class="nav allignRight">

        <div class="dropdown">
                <form action="{{ url_for('students.about') }}">
                    <button class="navigationBarButton" type="submit">About</button>
                </form>
        </div>

        {% if current_user.is_authenticated %}
            <div class="dropdown">
                <form action="{{ url_for('students.account') }}">
                    <button class="navigationBarButton" type="submit">Home page</button>
                </form>
            </div>

            <div class="dropdown">
                <form action="{{ url_for('leaderboard.leaderboard') }}">
                    <button class="navigationBarButton" type="submit">Leaderboards</button>
                </form>
            </div>

            {% if current_user.Role=='student' %}
                <div class="dropdown">
                    <form action="{{ url_for('games.turtle_game') }}">
                        <button class="navigationBarButton" type="submit">Turtle swim</button>
                    </form>
                </div>

                <div class="dropdown">
                    <form action="{{ url_for('games.pollution_game') }}">
                        <button class="navigationBarButton" type="submit">Pollution Game</button>

                    </form>
                </div>
            {% endif %}

            {% if current_user.Role=='parent' %}
                <div class="dropdown">
                    <form action="{{ url_for('parents.parent_view_student') }}">
                        <button class="navigationBarButton" type="submit">View your child</button>
                    </form>
                </div>
            {% endif %}

            {% if current_user.Role=='teacher'%}
                <div class="dropdown">
                    <form action="{{ url_for('teachers.teacher_view_school') }}">
                        <button class="navigationBarButton" type="submit" >View students</button>
                    </form>
                </div>
            {% endif %}

            <div class="dropdown">
                <form action="{{ url_for('students.logout') }}">
                    <button class="navigationBarButton" type="submit">Logout</button>
                </form>
            </div>

        {% endif %}


        {% if not current_user.is_authenticated %}
            <div class="dropdown">
                <form action="{{ url_for('students.index') }}">
                    <button class="navigationBarButton" type="submit">Home page</button>
                </form>
            </div>

            <div class="dropdown">
                <form action="{{ url_for('students.login') }}">
                    <button class="navigationBarButton" type="submit">Login</button>
                </form>
            </div>

            <div class="dropdown">
                <button class="navigationBarButton">Register</button>
                <div class="dropdown-content">
                    <a href="{{ url_for('students.student_register') }}">Student register</a>
                    <a href="{{ url_for('students.teacher_register') }}">Teacher register</a>
                    <a href="{{ url_for('students.parent_register') }}">Parent register</a>
                </div>
            </div>
        {% endif %}

    </div>

    {% block content %}
    {% endblock %}

</div>

<div class="mobile">
    <div class="mobileBox">
        <h2 class="center">
            Sorry this page is not mobile compatible
        </h2>
    </div>
</div>

</body>


</html>

templates/gameBase.html
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | - Save The Turtles!</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <link rel="shortcut icon" href={{ url_for('static', filename='PollutionGame/TemplateData/favicon.ico') }}>
    <link rel="stylesheet" href={{ url_for('static', filename='PollutionGame/TemplateData/style.css') }}>
</head>

<body>

<div class="computerGame">
    <div class="nav allignRight">

        {% if current_user.is_authenticated %}
            <div class="dropdown">
                <form action="{{ url_for('students.account') }}">
                    <button class="navigationBarButton" type="submit">Home page</button>
                </form>
            </div>

            <div class="dropdown">
                <form action="{{ url_for('leaderboard.leaderboard') }}">
                    <button class="navigationBarButton" type="submit">Leaderboards</button>
                </form>
            </div>

            {% if current_user.Role=='student' %}
                <div class="dropdown">
                    <form action="{{ url_for('games.turtle_game') }}">
                        <button class="navigationBarButton" type="submit">Turtle swim</button>
                    </form>
                </div>

                <div class="dropdown">
                    <form action="{{ url_for('games.pollution_game') }}">
                        <button class="navigationBarButton" type="submit">Pollution Game</button>

                    </form>
                </div>
            {% endif %}

            {% if current_user.Role=='parent' %}
                <div class="dropdown">
                    <form action="{{ url_for('parents.parent_view_student') }}">
                        <button class="navigationBarButton" type="submit">View your child</button>
                    </form>
                </div>
            {% endif %}

            <div class="dropdown">
                <form action="{{ url_for('students.logout') }}">
                    <button class="navigationBarButton" type="submit">Logout</button>
                </form>
            </div>

        {% endif %}


        {% if not current_user.is_authenticated %}
            <div class="dropdown">
                <form action="{{ url_for('students.index') }}">
                    <button class="navigationBarButton" type="submit">Home page</button>
                </form>
            </div>

            <div class="dropdown">
                <form action="{{ url_for('students.login') }}">
                    <button class="navigationBarButton" type="submit">Login</button>
                </form>
            </div>

            <div class="dropdown">
                <button class="navigationBarButton">Register</button>
                <div class="dropdown-content">
                    <a href="{{ url_for('students.studentRegister') }}">Student register</a>
                    <a href="{{ url_for('students.teacherRegister') }}">Teacher register</a>
                    <a href="{{ url_for('students.parentRegister') }}">Parent register</a>

                </div>
            </div>
        {% endif %}

    </div>

    {% block content %}
    {% endblock %}

</div>

<div class="mobileGame">
    <div class="mobileBox">
        <div class="Center">
            <b>Sorry this page is not mobile compatible <br> <br>
                The screen has to be atleast 960 by 720 pixels</b>
        </div>
    </div>
</div>

</body>

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="welcome">
        <h1 class="center">
            Welcome to your Virtual Environment!
        </h1>

        <div class="indexLoginPosition">
            <b class="indexPaddingLeft indexButtonAlign">User login</b>
            <a class="button4" href="{{ url_for('students.login') }}">Login</a>
        </div>

        <div class="indexRegisterPosition">
            <b class="indexPaddingLeft">Register as:</b>
            <a class="button1" style="padding-right: 20px" href="{{ url_for('students.student_register') }}">Student</a>
            <a class="button1" style="padding-right: 20px" href="{{ url_for('students.teacher_register') }}">Teacher</a>
            <a class="button1" style="padding-right: 20px" href="{{ url_for('students.parent_register') }}">Parent</a>
        </div>
    </div>
{% endblock %}

templates/leaderboard.html
{% extends "base.html" %}

{% block content %}

    <div class="leaderboardBox">
        <div class="header">Leaderboard</div>

        <table>
            <tr>
                <th class="tableHeader">Student ID</th>
                <th class="tableHeader">Firstname</th>
                <th class="tableHeader">Lastname</th>
                <th class="tableHeader">Points</th>
                <th class="tableHeader">SIC</th>
            </tr>

            {% for student in Students %}
                <tr>
                    <td>{{ student.StudentID }}</td>
                    <td>{{ student.FirstName }}</td>
                    <td>{{ student.LastName }}</td>
                    <td>{{ student.Points }}</td>
                    <td>{{ student.SIC }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>



{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

    <div class="login">
        <p class="inputField" id='name'><b>Login</b></p>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}

        <form method="POST">
            <div class="inputField">
                {{ form.csrf_token() }}
                {{ form.username(class="input", placeholder="Username") }}
                {% for error in form.username.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.password(class="input", placeholder="Password") }}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </div>
            <div class="center">
                {{ form.submit(class="button1") }}
            </div>
        </form>
    </div>
{% endblock %}

templates/parentRegister.html
{% extends "base.html" %}

{% block content %}

    <div class="register">
        <p class="inputField" id='name'><b>Parent register</b></p>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}. Go to <a href="{{ url_for('students.login') }}">login page</a>.
                </div>
            {% endif %}
        {% endwith %}

        <form method="POST">
            <div class="inputField">
                {{ form.csrf_token() }}
                {{ form.firstname(class="input", placeholder="First Name") }}
                {% for error in form.firstname.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.lastname(class="input", placeholder="Last Name") }}
                {% for error in form.lastname.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.email(class="input", placeholder="Email") }}
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.password(class="input", placeholder="Password") }}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                {% for error in form.confirm_password.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.sic(class="input", placeholder="SIC (School Individual Code") }}
                {% for error in form.sic.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.student_id(class="input", placeholder="Student ID") }}
                {% for error in form.student_id.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="center">
                {{ form.submit(class="button1") }}
            </div>
        </form>
    </div>

{% endblock %}

templates/reset_password.html
{% extends "base.html" %}

{% block content %}

    <div class="login">
        <p class="inputField" id='name' ><b>Reset Password</b></p>

        {% with messages = get_flashed_messages() %}

            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}

        {% endwith %}

        <form method="POST">
            {{ form.csrf_token() }}
            <div class="inputField">
                {{ form.student_id(class="input", placeholder="Student ID") }}
                {% for error in form.student_id.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.password(class="input", placeholder="Password") }}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="inputField">
                {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                {% for error in form.confirm_password.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="center">
                {{ form.submit(class="button1") }}
            </div>
        </form>
    </div>
{% endblock %}

templates/teacherViewSchool.html
{% extends "base.html" %}

{% block content %}

    <div class="leaderboardBox">
        <div class="header" >Students in this school</div>

            <table>
                <tr>
                    <th class="tableHeader">Student ID</th>
                    <th class="tableHeader">Firstname</th>
                    <th class="tableHeader">Lastname</th>
                    <th class="tableHeader">Points</th>
                    <th class="tableHeader">SIC</th>
                </tr>

                {% for student in Students %}
                    <tr>
                        <td>{{ student.StudentID }}</td>
                        <td>{{ student.FirstName }}</td>
                        <td>{{ student.LastName }}</td>
                        <td>{{ student.Points }}</td>
                        <td>{{ student.SIC }}</td>
                    </tr>
                {% endfor %}
            </table>
        <div class="center" style="margin: 20px">
            <a class="button1" style="padding-right: 20px;" href="{{ url_for('teachers.reset_password') }}">Reset student password</a>
        </div>
    </div>

{% endblock %}